times = ('Fluminense', 'Botafogo', 'Fortaleza', 'Palmeiras', 'Vasco da gama', 'Internacional', 'Bragantino', 'Flamengo', 'São paulo', 'Goias', 'Athletico PR', 'Cruzeiro', 'Gremio', 'Corinthians', 'Cuiaba', 'Atletico MG', 'Santos', 'Bahia', 'Curitiba', 'America MG')
print('-='*20)
print(f'Lista de times do Brasileirão {times}')
print('-='*20)
print(f'OS 5 primeiros colocados são: {times[:5]}') 
print('-='*20)
print(f'Os 4 ultimos são: {times[-4:]}')
print('-='*20)
print(f'Times em oredem alfabetica {sorted(times)}')
print('-='*20)
print(f'O Palmeiras esta na {times.index("Palmeiras")+1}ª posição ' )
